spring:
  application:
    name: openplatform
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  threads:
    virtual:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/openplatform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&createDatabaseIfNotExist=true
    username: root
    password: 200594
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

server:
  port: 8000

sa-token:
  token-name: Authorization
  timeout: 86400
  active-timeout: 1800
  is-concurrent: true
  is-share: false
  token-style: tik
  is-log: true
  jwt-secret-key: openplatform-jwt-secret-key-2024

continew-starter:
  web:
    response:
      enabled: true
      custom-success-code: 0
      custom-error-code: 1
  auth:
    satoken:
      enabled: false
      security:
        excludes:
          - /auth/login
          - /captcha/**
          - /open-api/**
          - /doc.html
          - /webjars/**
          - /v3/api-docs/**
          - /swagger-resources/**
          - /swagger-ui/**
  log:
    interceptor:
      enabled: false
  trace:
    enabled: false
  encrypt:
    password-encoder:
      enabled: true
    field:
      enabled: false
      private-key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCPawG3FKfpYbsb
        dQWJXNHXOAJ7I7+E0Ef6G6vPFbNZODKryXYBzh2KZLMbrmTguiA2nqNxtzm9sfoL
        9qn1LGLVyMqGGq1nH5nf3MasinQIZ2jELFja2QwCQvIcn8ZZ90bSA7f6O0a2s5vl
        /ugI2qDh8LlHoF9+V7Kb3GKLMUvanqTzlL38IwffR5/Ltd/wJMC7puxyQ3OEyYUg
        Zq+m/ytR3ZdIdlvbvcy30HjTUQCCTi44Bbam4UKRxhk7iHM7T5hDAdr43R6inl9K
        bCmsN3cJ2SzqkF47uo+ULCoZeS+shaW2HANW0Xfl/ovZRMSOo3jYLAFhCejKB1Ua
        bYFa1Nn1AgMBAAECggEAXcpiDcPxZ3vlbDhkTYepJ3FWlgcz2XyIhbUQ79XGO2O4
        J4YRqW6M/ROL2l97U0gFhxLJ2rUziq3Y03gVf+PuItc0Mu1BV35gF/l+6BmHdnOC
        HUDPPxfQda4oPbXzdqRy6SdLatbXEOZ23ruMLTYlHn1Z/dCQgsSBZtKCk3rCm45F
        F5r7ZoAxbIF7cG0drDxE0znr+oxx1xDBk7lxTYqEe4a4aleTm5RxfRD68H71dgET
        2IEVBgoaJF+PeknQ/bYdsipKZVEWBIqiRG24MwcjQ7rZGFq92x/zeAZp6XzXVxle
        bz69bEC/SYdyRJ6tFuz1Q6nOHXpp6N/nzOGPWnGBQQKBgQDdjg5cNTWckq09HX1T
        +2/HISxWkK15F7WBMpQ5WSjsm/lP3xf7GunoifMkClphhgNOuNNH1tXEWmn1Z5ub
        FWkSmQx4JivyjqOWm9V8F003j2lROK59WH0tGA1UQ4zwMv0QzNZ+eSiT7DoMw/K8
        J983v79LLWRHI5nwKji2hr6gRQKBgQCltxSyRfcXCfM5LJiLnQK21uRchmFlGiaC
        l1T2MZLI8GuwW680tPPyys9ui0YopCaLsnbeg7C5oKk5LrbSefiKW2gelT6C08Vq
        ZxErjKPrUwzBBJSdkODSiK0yq3Ssix63uwbnvoJWSuzhr7gBwwIulk0CCklJD8yn
        oorKjb4l8QKBgQDbj3L1uBl4H/ekkDvqZUvhqCNbaicv0Oojri8sIgqnaO8KU0ld
        pM9XjpYxCj2FVhyjABEJqYLRAtTsyQ9xAifNsXSlARceWnMNx0MqpaD1RZ8WSbjK
        KU5ryOE0t3jNdYpLAuQyE/m9liX1Dp7YDh9tDQ4S/1nYEhT057KqWCBDjQKBgERv
        lFt/K2jXUhvlf+YAZJOPsWVIlcZEA21hA9RcaqsTJtYBNx0EMc6t1PZpDANSrxx4
        CkEgj4ZJhDk6QoQvnOW+lAQ1TEiJHnkvsVaT0Uoo1RaNRra/kyk/Co/nYNq05W2p
        DlP8SCVM8gDOKaaIm0kUBx91kghbPwBnzvuRh9pxAoGARYK9TSSQlTIJAJUCB0Ml
        boA34q2nNI4QKHHx7ymlAg7tgwL/3rZQp8yld/03plBeBbM4cGn4Wu2WNWQ2Zmj2
        6G48z9YSBMRbVNqONsJLJTgcpTtO40LtkPokbdBsbbDh8sh7Ej8dzsTomv2dXVXP
        l/K+cnydE8DYok+DpbX6JAw=
        -----END PRIVATE KEY-----
      public-key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj2sBtxSn6WG7G3UFiVzR
        1zgCeyO/hNBH+hurzxWzWTgyq8l2Ac4dimSzG65k4LogNp6jcbc5vbH6C/ap9Sxi
        1cjKhhqtZx+Z39zGrIp0CGdoxCxY2tkMAkLyHJ/GWfdG0gO3+jtGtrOb5f7oCNqg
        4fC5R6Bffleym9xiizFL2p6k85S9/CMH30efy7Xf8CTAu6bsckNzhMmFIGavpv8r
        Ud2XSHZb273Mt9B401EAgk4uOAW2puFCkcYZO4hzO0+YQwHa+N0eop5fSmwprDd3
        Cdks6pBeO7qPlCwqGXkvrIWlthwDVtF35f6L2UTEjqN42CwBYQnoygdVGm2BWtTZ
        9QIDAQAB
        -----END PUBLIC KEY-----
  captcha:
    graphic:
      expirationInMinutes: 5
    behavior:
      enabled: false
  cache:
    jetcache:
      enabled: false
  ratelimiter:
    enabled: false
  data:
    mybatis-plus:
      enabled: true
  extension:
    crud:
      mybatis-plus:
        enabled: true
    datapermission:
      mybatis-plus:
        enabled: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 0
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  group-configs:
    - group: default
      display-name: 全部接口
      paths-to-match: /**
    - group: open-platform
      display-name: 开放平台
      paths-to-match: /open-platform/**, /open-api/**

logging:
  level:
    com.openplatform: debug
    top.continew: info