spring:
  application:
    name: openplatform
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  threads:
    virtual:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/openplatform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&createDatabaseIfNotExist=true
    username: root
    password: 200594
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

server:
  port: 8000

sa-token:
  token-name: Authorization
  timeout: 86400
  active-timeout: 1800
  is-concurrent: true
  is-share: false
  token-style: tik
  is-log: true
  jwt-secret-key: openplatform-jwt-secret-key-2024

continew-starter:
  web:
    response:
      enabled: true
      custom-success-code: 0
      custom-error-code: 1
  auth:
    satoken:
      enabled: false
      security:
        excludes:
          - /auth/login
          - /captcha/**
          - /open-api/**
          - /doc.html
          - /webjars/**
          - /v3/api-docs/**
          - /swagger-resources/**
          - /swagger-ui/**
  log:
    interceptor:
      enabled: false
  trace:
    enabled: false
  encrypt:
    password-encoder:
      enabled: true
    field:
      enabled: false
      private-key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC8Tib4SzuRb285
        PcxDV1A6p2O1JPbajU9dKnG6zRR8+ppHzKWB/gXO0J5N/DY6DP+laHXuGzuedT07
        hKCW4GTk23Wwx1MmisY4/QINAVN6p1nqOD4jEAtChz1w5JSqGSQ/VPTRaJykA5T+
        /fMLuv6iH38d+jvKRiXQSSN01LOyWGvbPTxyL7FEIvdNI8QTdbjmv7ahmcl2oMpv
        M++Akny7FNpH+1BA07rlYRrAlocM/TxmCpuACePgJLXG753RELaqXaS7ZvtszuUZ
        bnbHHnC3CwiN5L1q4EZ0UP1fqFBQLWcIvLz5yOC0wUUC416tkCjVczP6peKDLpmb
        8l38Gr73AgMBAAECggEAQAMXN0en38gwWJab5fZ8BPxbJjyDGAd6h7LCh5xojxXH
        tYmpZ7e5NLVxYxROQMyjaRDKKh+i1DqJjr6GstNkKPI7n1Ua/JqnSL8lX9NoE+Vo
        6PimktfE5CBCMCrcKLi0PD0+niNAQHchQs+EPCQcpHMtjLzAb4IKH7SFM5WM4p6a
        UWUtBwQ24eGBVXapuTxmzMGmi+IY/r1+8hqwYrHl0qdHZsAsN7beqWu3nSqbNHPR
        Hznc4b+emQPTuE8ctC0igx23BgJLmW1+xJIIphMnl53Z/aQLpELbr+Pe8Ug8Rab3
        JqqfLb47LB6HNrh/Wjj1Qp7ZbChSw6rxCNDY15pZEQKBgQD/I/mbBWxAjaboKWz1
        1MCfWvlOL4EGbH8KWa619u1ns99qteo3fwIeADdKJUQGuHjYKpqLzNszFMshudSe
        VHwp29DMXR9BSma35ToFSZaW2+2tOGkBSmSfBJ+rXTNhZH7o7SpuVDbur6pzldEp
        8h+6GPvniMIkVRxn/25sC6/dcQKBgQC88IpnZjvcPlqy1tcKjOPbGM2sKUKPuRwP
        aQvUSu4VaCIf7rv6bZzL31PNXh0MDw3uVcZqCMuZwOfSS7uYO1qiPAbwrLmSad4l
        STN1VTMqucqts2XmH2K5opFlEjzLOy81zjHEqOu1ICXckEnNydbnIZWsn6Y4tSCC
        VnZmt0nO5wKBgFoM/X08hb+m/2DzthRyGeZkupdg5t44jwI9Mw/gblxqvREx0c/y
        kPG7y8fsrTzeATDyoId1L2yxCx0FNMkJMqWnguOOfoiR1P1U94yEM5VdXF8GCPG+
        qxMBE8Xs6ESYrr5Rbudv68+Eytlu6FswrQgG52oJ99PRAmymV/fkjBbRAoGAZtK5
        X8BBf4Dnt0A4U2ONdWUwOStTMAhbfv96EpScsUW0nJA9+PHCTSlC4BcB09g1iqlf
        i8ExnIFhKA9TDmvuzS/BzyUQ8N9wp/YIbShq6iumY5WoNO6Lud8BJXIhZ7DT5oJK
        j24mqLHQKRLVN4tKywp5/DH+MgpQoN4RHaFOJ60CgYAPLs+UK1F7m+0cJysAdEGl
        uc9l/36dR/vuj7XB+BInnj2Jw8SKtPcTJR3Notvn2+EoNr+aeXK9/hhHc7gVxESi
        XWWj+TskpBWL78dx62qxzx/nqhnFDOccKmO7vGRSemSl9/wGNHuciaoMnTyjOUAH
        sSxIvKELpa+0Ij7gk87baA==
        -----END PRIVATE KEY-----
      public-key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvE4m+Es7kW9vOT3MQ1dQ
        OqdjtST22o1PXSpxus0UfPqaR8ylgf4FztCeTfw2Ogz/pWh17hs7nnU9O4SgluBk
        5Nt1sMdTJorGOP0CDQFTeqdZ6jg+IxALQoc9cOSUqhkkP1T00WicpAOU/v3zC7r+
        oh9/Hfo7ykYl0EkjdNSzslhr2z08ci+xRCL3TSPEE3W45r+2oZnJdqDKbzPvgJJ8
        uxTaR/tQQNO65WEawJaHDP08ZgqbgAnj4CS1xu+d0RC2ql2ku2b7bM7lGW52xx5w
        twsIjeS9auBGdFD9X6hQUC1nCLy8+cjgtMFFAuNerZAo1XMz+qXigy6Zm/Jd/Bq+
        9wIDAQAB
        -----END PUBLIC KEY-----
  captcha:
    graphic:
      expirationInMinutes: 5
    behavior:
      enabled: false
  cache:
    jetcache:
      enabled: false
  ratelimiter:
    enabled: false
  data:
    mybatis-plus:
      enabled: true
  extension:
    crud:
      mybatis-plus:
        enabled: true
    datapermission:
      mybatis-plus:
        enabled: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 0
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  group-configs:
    - group: default
      display-name: 全部接口
      paths-to-match: /**
    - group: open-platform
      display-name: 开放平台
      paths-to-match: /open-platform/**, /open-api/**

logging:
  level:
    com.openplatform: debug
    top.continew: info